apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: phonebook
    {{- include "operator.labels" . | nindent 4 }}

  name: phonebook:providers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: phonebook:providers
subjects:
- kind: ServiceAccount
  name: phonebook-providers
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: phonebook
    {{- include "operator.labels" . | nindent 4 }}
  name: phonebook:providers-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: phonebook:providers-leader-election
subjects:
- kind: ServiceAccount
  name: phonebook-providers
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: phonebook
    {{- include "operator.labels" . | nindent 4 }}

  name: phonebook:providers-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: phonebook:providers-events
subjects:
- kind: ServiceAccount
  name: phonebook-providers
  namespace: {{ .Release.Namespace }}
